[features]
seeds = false
[programs.localnet]
solidea = "FvfiKfUPLZvrAJnmeAZtMZi51FvYuoWr9WvozxDrb6aE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/rathin.kumar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
